# Generated by Django 4.1.2 on 2022-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proveedor",
            old_name="datalle",
            new_name="detalle",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="estado",
            field=models.BooleanField(
                default=True, verbose_name="Estado interno del proveedor"
            ),
        ),
    ]
