# Generated by Django 4.1.2 on 2022-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rut",
            field=models.CharField(max_length=10, unique=True, verbose_name="Rut"),
        ),
    ]
