# Generated by Django 4.1.2 on 2022-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_alter_usuario_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rut",
            field=models.CharField(max_length=9, unique=True, verbose_name="Rut"),
        ),
    ]
